import type { Metadata } from "next";
import { Fustat, Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const nohemi = localFont({
  src: [
    {
      path: "../public/Fonts/Nohemi-Font/Nohemi-Bold-BF6438cc577b524.woff",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-nohemi",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-outfit",
});

const fustat = Fustat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-fustat",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${nohemi.variable} ${outfit.variable} ${fustat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
